const Data= [
     {
      "Address": "Lang Chánh",
      "Area": "KV1",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(88)",
      "Faculty": "CNTT-TT",
      "Nation": "Khác",
      "Result": "Khá",
      "Sex": "Nam",
      "Test_score": "20",
    }, {
      "Address": "Yên Định",
      "Area": "KV2",
      "Block": "D",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(88)",
      "Faculty": "Ngoại ngữ",
      "Nation": "Khác",
      "Result": "Khá",
      "Sex": "Nam",
      "Test_score": "18",
    }, {
      "Address": "Như Xuân",
      "Area": "KV3",
      "Block": "D",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(88)",
      "Faculty": "Ngoại ngữ",
      "Nation": "Khác",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "29",
    }, {
      "Address": "Đông Sơn",
      "Area": "KV2",
      "Block": "B",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(86)",
      "Faculty": "Tiểu học",
      "Nation": "Khác",
      "Result": "Giỏi",
      "Sex": "Nam",
      "Test_score": "24.5",
    }, {
      "Address": "Thọ Xuân",
      "Area": "KV2",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Luật",
      "Nation": "Kinh",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "31",
    }, {
      "Address": "Đông Sơn",
      "Area": "KV1",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(36),Khối kiến thức giáo dục chuyên nghiệp(90)",
      "Faculty": "KTCN",
      "Nation": "Kinh",
      "Result": "TB",
      "Sex": "Nữ",
      "Test_score": "16",
    }, {
      "Address": "Thiệu Hóa",
      "Area": "2NT",
      "Block": "C",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(84)",
      "Faculty": "Xã hội",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nam",
      "Test_score": "22",
    }, {
      "Address": "Quảng Xương",
      "Area": "2NT",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Luật",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nữ",
      "Test_score": "24",
    }, {
      "Address": "Bá Thước",
      "Area": "2NT",
      "Block": "C",
      "Education_program": "Khối kiến thức giáo dục đại cương(46),Khối kiến thức giáo dục chuyên nghiệp(67)",
      "Faculty": "TL-GD",
      "Nation": "Kinh",
      "Result": "Xuất sắc",
      "Sex": "Nữ",
      "Test_score": "27.5",
    }, {
      "Address": "Nga Sơn",
      "Area": "KV2",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "GDTC",
      "Nation": "Kinh",
      "Result": "TB",
      "Sex": "Nữ",
      "Test_score": "17",
    }, {
      "Address": "Hà Trung",
      "Area": "2NT",
      "Block": "B",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(88)",
      "Faculty": "CNTT-TT",
      "Nation": "Kinh",
      "Result": "TB",
      "Sex": "Nữ",
      "Test_score": "17",
    }, {
      "Address": "Hà Trung",
      "Area": "KV1",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Luật",
      "Nation": "Kinh",
      "Result": "Xuất sắc",
      "Sex": "Nữ",
      "Test_score": "29.5",
    }, {
      "Address": "Thiệu Hóa",
      "Area": "KV1",
      "Block": "C",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(84)",
      "Faculty": "Xã hội",
      "Nation": "Khác",
      "Result": "TB",
      "Sex": "Nam",
      "Test_score": "15",
    }, {
      "Address": "Hà Trung",
      "Area": "KV3",
      "Block": "D",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(84)",
      "Faculty": "Ngoại ngữ",
      "Nation": "Kinh",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "31.5",
    }, {
      "Address": "Thiệu Hóa",
      "Area": "2NT",
      "Block": "B",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Luật",
      "Nation": "Khác",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "27",
    }, {
      "Address": "Nga Sơn",
      "Area": "2NT",
      "Block": "A1",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(86)",
      "Faculty": "Tiểu học",
      "Nation": "Khác",
      "Result": "Giỏi",
      "Sex": "Nam",
      "Test_score": "23",
    }, {
      "Address": "Như Thanh",
      "Area": "KV1",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "GDTC",
      "Nation": "Kinh",
      "Result": "Khá",
      "Sex": "Nam",
      "Test_score": "18",
    }, {
      "Address": "Lang Chánh",
      "Area": "2NT",
      "Block": "D",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "Ngoại ngữ",
      "Nation": "Khác",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "31.25",
    }, {
      "Address": "Yên Định",
      "Area": "2NT",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "Mầm non",
      "Nation": "Kinh",
      "Result": "TB",
      "Sex": "Nam",
      "Test_score": "17.5",
    }, {
      "Address": "TP Thanh Hóa",
      "Area": "2NT",
      "Block": "D",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "Ngoại ngữ",
      "Nation": "Khác",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "32",
    },{
      "Address": "Thiệu Hóa",
      "Area": "KV1",
      "Block": "A1",
      "Education_program": "Khối kiến thức giáo dục đại cương(44),Khối kiến thức giáo dục chuyên nghiệp(82)",
      "Faculty": "N-L-N Nghiệp",
      "Nation": "Kinh",
      "Result": "Xuất sắc",
      "Sex": "Nữ",
      "Test_score": "30",
    }, {
      "Address": "Quan Sơn",
      "Area": "2NT",
      "Block": "B",
      "Education_program": "Khối kiến thức giáo dục đại cương(44),Khối kiến thức giáo dục chuyên nghiệp(82)",
      "Faculty": "N-L-N Nghiệp",
      "Nation": "Khác",
      "Result": "Khá",
      "Sex": "Nữ",
      "Test_score": "19",
    }, {
      "Address": "Triệu Sơn",
      "Area": "KV3",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(44),Khối kiến thức giáo dục chuyên nghiệp(82)",
      "Faculty": "Mầm non",
      "Nation": "Kinh",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "29",
    }, {
      "Address": "Thiệu Hóa",
      "Area": "KV1",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(44),Khối kiến thức giáo dục chuyên nghiệp(62)",
      "Faculty": "KT-QTKD",
      "Nation": "Khác",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "27",
    }, {
      "Address": "Hậu Lộc",
      "Area": "KV2",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "GDTC",
      "Nation": "Khác",
      "Result": "Khá",
      "Sex": "Nữ",
      "Test_score": "20",
    }, {
      "Address": "Vĩnh Lộc",
      "Area": "KV3",
      "Block": "A1",
      "Education_program": "Khối kiến thức giáo dục đại cương(36),Khối kiến thức giáo dục chuyên nghiệp(90)",
      "Faculty": "KTCN",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nữ",
      "Test_score": "23",
    }, {
      "Address": "Vĩnh Lộc",
      "Area": "KV2",
      "Block": "C",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(84)",
      "Faculty": "Xã hội",
      "Nation": "Kinh",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "31.5",
    }, {
      "Address": "TP Sầm Sơn",
      "Area": "KV1",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(36),Khối kiến thức giáo dục chuyên nghiệp(90)",
      "Faculty": "KTCN",
      "Nation": "Kinh",
      "Result": "Khá",
      "Sex": "Nữ",
      "Test_score": "19.5",
    }, {
      "Address": "Khác",
      "Area": "KV3",
      "Block": "B",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(88)",
      "Faculty": "CNTT-TT",
      "Nation": "Kinh",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "27",
    },{
      "Address": "Cẩm Thủy",
      "Area": "KV1",
      "Block": "A1",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Luật",
      "Nation": "Kinh",
      "Result": "Khá",
      "Sex": "Nam",
      "Test_score": "20",
    }, {
      "Address": "Hà Trung",
      "Area": "KV3",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Mầm non",
      "Nation": "Khác",
      "Result": "Khá",
      "Sex": "Nữ",
      "Test_score": "18.5",
    }, {
      "Address": "Nga Sơn",
      "Area": "KV1",
      "Block": "B",
      "Education_program": "Khối kiến thức giáo dục đại cương(42),Khối kiến thức giáo dục chuyên nghiệp(88)",
      "Faculty": "CNTT-TT",
      "Nation": "Kinh",
      "Result": "Khá",
      "Sex": "Nữ",
      "Test_score": "19",
    },
     {
      "Address": "Quan Hóa",
      "Area": "2NT",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "GDTC",
      "Nation": "Khác",
      "Result": "Giỏi",
      "Sex": "Nữ",
      "Test_score": "21.5",
    }, 
    {
      "Address": "Nga Sơn",
      "Area": "KV2",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "GDTC",
      "Nation": "Kinh",
      "Result": "Khá",
      "Sex": "Nữ",
      "Test_score": "19.5",
    },
     {
      "Address": "Đông Sơn",
      "Area": "KV1",
      "Block": "A1",
      "Education_program": "Khối kiến thức giáo dục đại cương(36),Khối kiến thức giáo dục chuyên nghiệp(90)",
      "Faculty": "KTCN",
      "Nation": "Khác",
      "Result": "Khá",
      "Sex": "Nam",
      "Test_score": "18.5",
    },
     {
      "Address": "Quan Sơn",
      "Area": "KV2",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "GDTC",
      "Nation": "Khác",
      "Result": "Giỏi",
      "Sex": "Nữ",
      "Test_score": "24.5",
    },
     {
      "Address": "Nga Sơn",
      "Area": "KV2",
      "Block": "D",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "Ngoại ngữ",
      "Nation": "Khác",
      "Result": "Xuất sắc",
      "Sex": "Nam",
      "Test_score": "27",
    }, 
    {
      "Address": "TP Sầm Sơn",
      "Area": "KV1",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(44),Khối kiến thức giáo dục chuyên nghiệp(62)",
      "Faculty": "KT-QTKD",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nữ",
      "Test_score": "21.5",
    },
     {
      "Address": "Đông Sơn",
      "Area": "KV1",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(44),Khối kiến thức giáo dục chuyên nghiệp(62)",
      "Faculty": "KT-QTKD",
      "Nation": "Khác",
      "Result": "TB",
      "Sex": "Nam",
      "Test_score": "15",
    },
     {
      "Address": "Thạch Thành",
      "Area": "2NT",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(44),Khối kiến thức giáo dục chuyên nghiệp(62)",
      "Faculty": "Mầm non",
      "Nation": "Khác",
      "Result": "Giỏi",
      "Sex": "Nam",
      "Test_score": "21.5",
    }, 
    {
      "Address": "Hoằng Hóa",
      "Area": "KV3",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(44),Khối kiến thức giáo dục chuyên nghiệp(62)",
      "Faculty": "KT-QTKD",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nữ",
      "Test_score": "24.5",
    },
     {
      "Address": "Quan Hóa",
      "Area": "KV3",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Luật",
      "Nation": "Kinh",
      "Result": "Khá",
      "Sex": "Nữ",
      "Test_score": "20.5",
    },
     {
      "Address": "Nông Cống",
      "Area": "2NT",
      "Block": "D",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Ngoại ngữ",
      "Nation": "Khác",
      "Result": "Xuất sắc",
      "Sex": "Nữ",
      "Test_score": "31.5",
    }, 
    {
      "Address": "Nông Cống",
      "Area": "2NT",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(45),Khối kiến thức giáo dục chuyên nghiệp(68)",
      "Faculty": "Luật",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nữ",
      "Test_score": "21.5",
    },
     {
      "Address": "Lang Chánh",
      "Area": "2NT",
      "Block": "B",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(86)",
      "Faculty": "Tiểu học",
      "Nation": "Kinh",
      "Result": "Khá",
      "Sex": "Nữ",
      "Test_score": "19.5",
    }, 
    {
      "Address": "Cẩm Thủy",
      "Area": "KV3",
      "Block": "A1",
      "Education_program": "Khối kiến thức giáo dục đại cương(36),Khối kiến thức giáo dục chuyên nghiệp(90)",
      "Faculty": "KTCN",
      "Nation": "Kinh",
      "Result": "Khá",
      "Sex": "Nam",
      "Test_score": "19.5",
    }, 
    {
      "Address": "Vĩnh Lộc",
      "Area": "KV2",
      "Block": "C",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(86)",
      "Faculty": "Tiểu học",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nam",
      "Test_score": "21",
    },
     {
      "Address": "Hậu Lộc",
      "Area": "KV2",
      "Block": "M",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "GDTC",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nam",
      "Test_score": "25",
    },
     {
      "Address": "Thọ Xuân",
      "Area": "KV3",
      "Block": "D",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(73)",
      "Faculty": "Ngoại ngữ",
      "Nation": "Khác",
      "Result": "TB",
      "Sex": "Nữ",
      "Test_score": "17.5",
    },
     {
      "Address": "Cẩm Thủy",
      "Area": "KV3",
      "Block": "A",
      "Education_program": "Khối kiến thức giáo dục đại cương(40),Khối kiến thức giáo dục chuyên nghiệp(86)",
      "Faculty": "Tiểu học",
      "Nation": "Kinh",
      "Result": "Giỏi",
      "Sex": "Nữ",
      "Test_score": "24.5",
    },
  ]
  export {Data}